version: '2'


services:

    db:
        extends:
            file: etc/docker/common/db/docker-compose.yml
            service: db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - 8181:80
        environment:
            PMA_USER: root
            PMA_PASSWORD:
            PMA_HOST: db
            PMA_PORT: 3306