version: '2'


services:
    data:
        image: alpine
        command: /bin/true
        volumes:
        - ./webroot:/var/www/html

    db:
        extends:
            file: etc/docker/common/db/docker-compose.yml
            service: db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - 8181:80
        environment:
            PMA_USER: root
            PMA_PASSWORD:
            PMA_HOST: db
            PMA_PORT: 3306
    web: &web
        build: etc/docker/dev/web
        ports:
        - "8000:80"
        links:
        - db
        environment:
        - WEBROOT="/var/www/html"
        volumes_from:
        - data
       
        